spring:
  application:
    name: secondhand-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://localhost:3306/campus_secondhand?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456 # 请确保这里与你的本地 MySQL 密码一致
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080

file:
  upload-dir: uploads/
